# Generated by Django 3.1.14 on 2023-03-12 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(help_text='The message text', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The timestamp of sending message text')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The user name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.CharField(help_text='The response_text', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The timestamp of sending message text')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbox.chatmessage')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbox.user'),
        ),
    ]
